### ISSUE TITLE
Could you please add the BEV [CVPR2022] to the summary?

### ISSUE THREAD

**Issue by Arthur151** [4DVLab/Vision-Centric-BEV-Perception#9]
Great work. This summary would be very helpful to the related researchers.

In our recent work, BEV, we also explore to learn the bird's-eye-view representation for monocular 3D human mesh recovery.

Putting People in their Place: Monocular Regression of 3D People in Depth
[[Code]](https://github.com/Arthur151/ROMP) [[Project Page]](https://arthur151.github.io/BEV/BEV.html) [[Paper]](https://arxiv.org/abs/2112.08274) [[Video]](https://youtu.be/Q62fj_6AxRI) [[RH Dataset]](https://github.com/Arthur151/Relative_Human)

Thanks for sharing such great work!
Best,
Yu

**Comment by 4DVLab** [comment]
Please feel free to submit a pull request to add the new paper or related project page. Thanks
